//
//  NetworkConstants.h
//  CHManagement
//
//  Created by Peng, Troy on 4/27/16.
//  Copyright © 2016 楚淮集团. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface NetworkConstants : NSObject

#define baseUrl @"http://114.215.95.68:8080/cherp/"
#define signInUrl @"api/signIn"
#define signUpUrl @"api/signUp"
#define signUpNewUrl @"api/signUpNew"
#define changePswdUrl @"api/changePswd"
#define getAdminGroupIdUrl @"api/getAdminGroupId"
#define createGroupUrl @"api/createGroup"
#define changeGroupUrl @"api/changeGroup"
#define getGroupsUrl @"api/getGroups"
#define getGroupByIdUrl @"api/getGroupById"
#define deleteGroupUrl @"api/deleteGroup"
#define getGroupsByUserIdURL @"api/getGroupsByUserId"
#define createRoleAndPermissionUrl @"api/createRoleAndPermission"
#define deleteRoleUrl @"api/deleteRole"
#define changeRoleUrl @"api/changeRole"
#define getRolesUrl @"api/getRoles"
#define getRolesByIdUrl @"api/getRoleById"
#define getRolePermissionByRoleIdUrl @"api/getRolePermissionByRoleId"
#define changeRolePermissionUrl @"api/changeRolePermission"
#define getPermissionsUrl @"api/getPermissions"
#define getUsersUrl @"api/getUsers"
#define getUserByIdUrl @"api/getUserById"
#define deleteUserUrl @"api/deleteUser"
#define changeUserUrl @"api/changeUser"
#define signUrl @"api/sign"
#define getSignStatusUrl @"api/getSignStatus"
#define createFileUrl @"api/createFile"
#define getUploadTokenUrl @"api/getUploadToken"
#define deleteFileUrl @"api/deleteFile"
#define getFilesUrl @"api/getFiles"
#define createMessageUrl @"api/createMessage"
#define deleteMessageUrl @"api/deleteMessage"
#define getMessagesUrl @"api/getMessages"
#define createActivityUrl @"api/createActivity"
#define getActivitiesByGroupIdUrl @"api/getActivitiesByGroupId"
#define changeActivityUrl @"api/changeActivity"
#define getActivityByIdUrl @"api/getActivityById"
#define getYesterdayActivityByIdUrl @"api/getYesterdayActivityById"
#define getYesterActivityUrl @"api/getYesterdayActivity"
#define createScheduleUrl @"api/createSchedule"
#define changeScheduleUrl @"api/changeSchedule"
#define getSchedulesUrl @"api/getSchedules"
#define getScheduleByIdUrl @"api/getScheduleById"
#define getYesterdayScheduleUrl @"api/getYesterdaySchedule"
#define getYesterdayScheduleByIdUrl @"api/getYesterdayScheduleById"
#define createAuditMaterialsUrl @"api/createAuditMaterials"
#define changeAuditMaterialsUrl @"api/changeAuditMaterials"
#define deleteAuditMaterialsUrl @"api/deleteAuditMaterials"
#define getAuditMaterialsListByStatusAndIn_offUrl @"api/getAuditMaterialsListByStatusAndIn_off"
#define getAuditMaterialsListByGroupIdAndStatusAndIn_offUrl @"api/getAuditMaterialsListByGroupIdAndStatusAndIn_off"
#define getAuditMaterialsByIdUrl @"api/getAuditMaterialsById"
#define auditAuditMaterialsUrl @"api/auditAuditMaterials"
#define createAuditOthersUrl @"api/createAuditOthers"
#define changeAuditOthersUrl @"api/changeAuditOthers"
#define deleteAuditOthersUrl @"api/deleteAuditOthers"
#define getAuditOthersListByStatusUrl @"api/getAuditOthersListByStatus"
#define getAuditOthersListByGroupIdAndStatusUrl @"api/getAuditOthersListByGroupIdAndStatus"
#define getAuditOthersByIdUrl @"api/getAuditOthersById"
#define auditAuditOthersUrl @"api/auditAuditOthers"
#define createBillUrl @"api/createBill"
#define changeBillUrl @"api/changeBill"
#define getBillByIdUrl @"api/getBillById"
#define getBillsByGroupIdUrl @"api/getBillsByGroupId"
#define createBillBuildingUrl @"api/createBillBuilding"
#define changeBillBuildingUrl @"api/changeBillBuilding"
#define getBillBuildingByIdUrl @"api/getBillBuildingById"
#define getBillBuildingsByGroupIdUrl @"api/getBillBuildingsByGroupId"
#define createBillMaterialsUrl @"api/createBillMaterials"
#define changeBillMaterialsUrl @"api/changeBillMaterials"
#define deleteBillMaterialsUrl @"api/deleteBillMaterials"
#define getBillMeterialsListByGroupIdAndStatusAndIn_offUrl @"api/getBillMaterialsListByGroupIdAndStatusAndIn_off"
#define getBillMaterialsByIdUrl @"api/getBillMaterialsById"
#define finishBillMaterialsUrl @"api/finishBillMaterials"
#define changeBillOthersUrl @"api/changeBillOthers"
#define deleteBillOthersUrl @"api/deleteBillOthers"
#define getBillOthersListByStatusUrl @"api/getBillOthersListByStatus"
#define getBillOthersListByGroupIdAndStatusUrl @"api/getBillOthersListByGroupIdAndStatus"
#define getBillOthersByIdUrl @"api/getBillOthersById"
#define finishBillOthersUrl @"api/finishBillOthers"
#define setDeviceTokenUrl @"api/setNotifyToken"
#define deleteDeviceTokenUrl @"api/deleteNotifyToken"
#define reportFileUrl @"api/reportFile"
@end
